<?php
    $path = $_SERVER['DOCUMENT_ROOT'];
    $path = $path . "/includes/db_connect.php";
    include $path;

	//////////////////////////////////////////////////////////////////////
	// Loot by Mob
	//////////////////////////////////////////////////////////////////////
	$loot = array (
		array ( "One Eyed Rat", "Rat Hide" ),
		array ( "One Eyed Rat", "Rat Tail" ),
		array ( "One Eyed Rat", "Rat Eye" ),
		array ( "One Eyed Rat", "Rat Foot" ),
		array ( "One Eyed Rat", "Rat Meat" ),
		array ( "Kikiri", "Kikiri Meat" ),
		array ( "Kikiri", "Kikiri Blood" ),
		array ( "Kikiri", "Kikiri Feather" ),
		array ( "Tloke Drone", "Tloke Drone Wax" ),
		array ( "Tloke Drone", "Tloke Drone Wing" ),
		array ( "Forrest Arangma", "Arangma Tooth" ),
		array ( "Forrest Arangma", "Arangma Talon" ),
		array ( "Forrest Arangma", "Arangma Egg Sac" ),
		array ( "Clacker", "Clacker Meat" ),
		array ( "Clacker", "Clacker Carapace" ),
		array ( "Clacker", "Clacker Full Carapace" ),
		array ( "Clacker", "Clacker Leg" ),
		array ( "Coamti", "Coamti Tongue" ),
		array ( "Coamti", "Coamti Tail" ),
		array ( "Coamti", "Coamti Talon" ),
		array ( "Coamti", "Coamti Blood" ),
		array ( "Coamti", "Coamti Eye" ),
		array ( "Mudobber Coamti", "Mudobber Coamti Tongue" ),
		array ( "Mudobber Coamti", "Mudobber Coamti Tail" ),
		array ( "Mudobber Coamti", "Mudobber Coamti Talon" ),
		array ( "Mudobber Coamti", "Mudobber Coamti Blood" ),
		array ( "Mudobber Coamti", "Mudobber Coamti Eye" ),
		array ( "Rogue", "Shortsword" ),
		array ( "Rogue", "Knife" ),
		array ( "Rogue", "Healing Potion" ),
		array ( "Diseased Rat", "Diseased Rat Hide" ),
		array ( "Diseased Rat", "Diseased Rat Blood" ),
		array ( "Weaver Arangma", "Weaver Arangma Blood" ),
		array ( "Weaver Arangma", "Weaver Arangma Silk" ),
		array ( "Weaver Arangma", "Weaver Arangma Hair" ),
		array ( "Jade Clacker", "Jade Clacker Talon" ),
		array ( "Jade Clacker", "Jade Clacker Carapace" ),
		array ( "Jade Clacker", "Jade Clacker Full Carapace" ),
		array ( "Tloke Queen", "Tloke Queen Armor" ),
		array ( "Tloke Queen", "Tloke Queen Jewel" ),
		array ( "Tloke Queen", "Tloke Queen Wing" ),
		array ( "Frost Arangma", "Frost Arangma Feeler" ),
		array ( "Frost Arangma", "Frost Arangma Quartz" ),
		array ( "Frost Arangma", "Frost Arangma Blood" ),
		array ( "Tefusangling", "Tefusangling Skin" ),
		array ( "Tefusangling", "Tefusangling Tooth" ),
		array ( "Tefusangling", "Tefusangling Claw" ),
		array ( "Tefusangling", "Lump of Lard" ),
		array ( "Vesper Arangma", "Vesper Arangma Eye" ),
		array ( "Vesper Arangma", "Vesper Arangma Feeler" ),
		array ( "Vesper Arangma", "Vesper Arangma Carapace" ),
		array ( "Thunder Clacker", "Thunder Clacker Leg" ),
		array ( "Thunder Clacker", "Thunder Clacker Tentacle" ),
		array ( "Thunder Clacker", "Thunder Clacker Full Carapace" ),
		array ( "Carkarass", "Carkarass Skull" ),
		array ( "Carkarass", "Carkarass Tail" ),
		array ( "Carkarass", "Carkarass Feather" ),
		array ( "Fire Carkarass", "Carkarass Fire Feather" ),
		array ( "Fire Carkarass", "Carkarass Fire Carapace" ),
		array ( "Cutthroat", "Knife" ),
		array ( "Cutthroat", "Shortsword" ),
		array ( "Cutthroat", "Mace" ),
		array ( "Cutthroat", "Leather Armor" ),
		array ( "Gladiator", "Shortsword" ),
		array ( "Gladiator", "Small Battle Axe" ),
		array ( "Gladiator", "Leather Armor" ),
		array ( "Tefusang", "Tefusang Skin" ),
		array ( "Tefusang", "Tefusang Tooth" ),
		array ( "Tefusang", "Tefusang Claw" ),
		array ( "Tefusang", "Lump of Lard" ),
		array ( "Tloke Warrior", "Tloke Warrior Stinger" ),
		array ( "Tloke Warrior", "Tloke Warrior Wing" ),
		array ( "Trepor", "Trepor Wiggly Feeler" ),
		array ( "Trepor", "Trepor Heart" ),
		array ( "Trepor", "Trepor Egg Sac" ),
		array ( "Trepor Warrior", "Trepor Warrior Skin" ),
		array ( "Trepor Warrior", "Trepor Warrior Talon" ),
		array ( "Eagle Gobble", "Eagle Gobble Skull" ),
		array ( "Eagle Gobble", "Eagle Gobble Necklace" ),
		array ( "Eagle Gobble", "Eagle Gobble Bracelet" ),
		array ( "Eagle Gobble", "Club" ),
		array ( "Serpent Gobble", "Serpent Gobble Skull" ),
		array ( "Serpent Gobble", "Serpent Gobble Amulet" ),
		array ( "Serpent Gobble", "Serpent Gobble Bones" ),
		array ( "Serpent Gobble", "Axe" ),
		array ( "Gobble", "Gobble Ear" ),
		array ( "Gobble", "Gobble Blood" ),
		array ( "Gobble", "Gobble Meat" ),
		array ( "Gobble", "Gobble Hair" ),
		array ( "Poison Carkarass", "Poison Carkarass Feather" ),
		array ( "Poison Carkarass", "Poison Carkarass Skull" ),
		array ( "Poison Carkarass", "Carkarass Poison" ),
		array ( "Sand Arangma", "Sand Arangma Talon" ),
		array ( "Sand Arangma", "Sand Arangma Blood" ),
		array ( "Sand Arangma", "Sand Arangma Silk" ),
		array ( "Mercenary", "Shortsword" ),
		array ( "Mercenary", "Small Battle Axe" ),
		array ( "Mercenary", "Leather Armor" ),
		array ( "Sapling Gorweal", "Sapling Gorweal roots" ),
		array ( "Sapling Gorweal", "Sapling Gorweal cortex" ),
		array ( "Gorweal", "Gorweal cortex" ),
		array ( "Gorweal", "Gorweal roots" ),
		array ( "Trepor Queen", "Trepor Queen Heart" ),
		array ( "Trepor Queen", "Trepor Queen Skin" ),
		array ( "Trepor Queen", "Trepor Queen Egg Sac" ),
		array ( "Riverling", "Riverling Skin" ),
		array ( "Riverling", "Riverling Skull" ),
		array ( "Riverling", "Riverling Tooth" ),
		array ( "Consumer", "Consumer Antenna" ),
		array ( "Consumer", "Consumer Leg" ),
		array ( "Consumer", "Consumer Blood" ),
		array ( "Consumer", "Chain Mail Torso Armor" ),
		array ( "Consumer", "Chain Mail Arms Armor" ),
		array ( "Consumer", "Chain Mail Pants" ),
		array ( "Armoured Riverling", "Armoured Riverling Hide" ),
		array ( "Armoured Riverling", "Armoured Riverling Skull" ),
		array ( "Armoured Riverling", "Falchion" ),
		array ( "Armoured Riverling", "Morning Star" ),
		array ( "Marfusang", "Marfusang Heart" ),
		array ( "Marfusang", "Marfusang Tongue" ),
		array ( "Marfusang", "Marfusang Bones" ),
		array ( "Dark Rogue", "Bows" ),
		array ( "Dark Rogue", "Sabre" ),
		array ( "Dark Rogue", "Dark Circle Ring" ),
		array ( "Dark Rogue", "Chain Mail Boots" ),
		array ( "Dark Rogue", "Chain Mail Gloves" ),
		array ( "Velnishi", "Velnishi Blood" ),
		array ( "Velnishi", "Velnishi Skin" ),
		array ( "Velnishi", "Velnishi Talon" ),
		array ( "Grendol", "Grendol Rib" ),
		array ( "Grendol", "Grendol Spine" ),
		array ( "Grendol", "Grendol Rotten Meat" ),
		array ( "Grendol", "Grendol Blood" ),
		array ( "Grendol", "Grendol Poison Blood" ),
		array ( "Flayed Velnishi", "Flayed Velnishi Skull" ),
		array ( "Flayed Velnishi", "Flayed Velnishi Talon" ),
		array ( "Onyx Dagger", "Golden Ring" ),
		array ( "Onyx Dagger", "Helms" ),
		array ( "Onyx Dagger", "Greater Potion of Healing" ),
		array ( "Onyx Dagger", "Dagger" ),
		array ( "Ulbernaut", "Ulbernaut Fur" ),
		array ( "Ulbernaut", "Ulbernaut Claw" ),
		array ( "Ulbernaut", "Ulbernaut Deadly Claw" ),
		array ( "Ulbernaut", "Ulbernaut Heart" ),
		array ( "Imago Consumer", "Imago Consumer Blood" ),
		array ( "Imago Consumer", "Broadsword" ),
		array ( "Imago Consumer", "Battle Axe" ),
		array ( "Imago Consumer", "Plate Armor" ),
		array ( "Toxic Grendol", "Toxic Grendol Blood" ),
		array ( "Toxic Grendol", "Fire Blood" ),
		array ( "Elder Gorweal", "Elder Gorweal roots" ),
		array ( "Elder Gorweal", "Elder Gorweal cortex" ),
		array ( "Vilenaut", "Vilenaut Fur" ),
		array ( "Vilenaut", "Vilenaut Blood" ),
		array ( "Neoten Consumer", "Neoten Consumer Blood" ),
		array ( "Neoten Consumer", "Claymore" ),
		array ( "Neoten Consumer", "Battle Axe" ),
		array ( "Neoten Consumer", "Plate Mail Torso Armor" ),
		array ( "Neoten Consumer", "Plate Mail Arms Armor" ),
		array ( "Maulbernaut", "Maulbernaut Fur" ),
		array ( "Maulbernaut", "Maulbernaut Talon" ),
		array ( "Maulbernaut", "Maulbernaut Perfect Talon" ),
		array ( "Maulberlord", "Maulberlord Blood" ),
		array ( "Maulberlord", "Maulberlord Talon" ),
		array ( "Maulberlord", "Maulberlord Perfect Talon" ),
		array ( "Maulberlord", "Maulberlord Ebony Heart" ),
		array ( "Expert Gladiator", "Shortsword" ),
		array ( "Expert Gladiator", "Longsword" ),
		array ( "Expert Gladiator", "Healing Potion" ),
		array ( "Expert Gladiator", "Greater Healing Potion" ),
		array ( "Expert Gladiator", "Round Shield" ),
		array ( "Dlayo Gladiator", "Shortsword" ),
		array ( "Dlayo Gladiator", "Longsword" ),
		array ( "Dlayo Gladiator", "Healing Potion" ),
		array ( "Dlayo Gladiator", "Greater Healing Potion" ),
		array ( "Dlayo Gladiator", "Round Shield" ),
		array ( "Marangma", "Weaver Arangma Silk" ),
		array ( "Marangma", "Arangma Egg Sac" ),
		array ( "Wrath Rat", "Wrath Rat Bones" ),
		array ( "Wrath Rat", "Wrath Rat Eye" ),
		array ( "Gawert", "Gawert stinger" ),
		array ( "Gawert", "Gawert Jaws" ),
		array ( "Gawert", "Gawert Carapace" ),
	);

	$mysqli->query("DROP TABLE IF EXISTS loot") or die($mysqli->error);
	$q = "CREATE TABLE IF NOT EXISTS loot (
					mob VARCHAR(50) NOT NULL,
					loot VARCHAR(50) NOT NULL,
					PRIMARY KEY (mob,loot)
					) ENGINE=MyISAM";
	$mysqli->query($q) or die($mysqli->error);

	foreach ($loot as $id => $vals)
	{
		$q = "INSERT INTO loot VALUES
			(
			\"".$vals[0]."\",
			\"".$vals[1]."\"
			)
		";
		$mysqli->query($q) or die ( $mysqli->error );
	}

	//////////////////////////////////////////////////////////////////////

	/* close connection */
	$mysqli->close();
